<?php
/*********************************************************************************
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2012 SugarCRM Inc.
 * 
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 * 
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 * 
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 * 
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 * 
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo. If the display of the logo is not reasonably feasible for
 * technical reasons, the Appropriate Legal Notices must display the words
 * "Powered by SugarCRM".
 ********************************************************************************/


// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  0 => 
  array (
    'acceptable_sugar_versions' => array(
        'exact_matches' => array(),
        'regex_matches' => array('6\\.[0-9]\\.[0-9]$'),
    ),
  ),
  1 => 
  array (
    'acceptable_sugar_flavors' => 
    array (
      0 => 'CE',
      1 => 'PRO',
      2 => 'ENT',
    ),
  ),
  'readme' => '',
  'key' => 'sc',
  'author' => '',
  'description' => '',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'StripePayments',
  'published_date' => '2013-03-07 00:34:56',
  'type' => 'module',
  'version' => '1',
  'remove_tables' => 'prompt',
);


$installdefs = array (
  'id' => 'StripePayments',
  'beans' => 
  array (
    0 => 
    array (
      'module' => 'sc_StripePayments',
      'class' => 'sc_StripePayments',
      'path' => 'modules/sc_StripePayments/sc_StripePayments.php',
      'tab' => true,
    ),
  ),
  'layoutdefs' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/sc_stripepayments_contacts_Contacts.php',
      'to_module' => 'Contacts',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/sc_stripepayments_accounts_Accounts.php',
      'to_module' => 'Accounts',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/sc_stripepayments_leads_Leads.php',
      'to_module' => 'Leads',
    ),
  ),
  'custom_fields'=>array (
	array(
	    'name' => 'stripe_customer_id',
	    'label' => 'LBL_STRIPE_CUSTOMER_ID',
	    'type' => 'varchar',
	    'module' => 'Accounts',
	    'help' => 'Stripe Customer',
	    'comment' => 'Stripe Customer ID',
	    'default_value' => '',
	    'max_size' => 255,
	    'required' => false, // true or false
	    'reportable' => true, // true or false
	    'audited' => false, // true or false
	    'importable' => 'true', // 'true', 'false', 'required'
	    'duplicate_merge' => false, // true or false
	),
	array(
	    'name' => 'stripe_customer_id',
	    'label' => 'LBL_STRIPE_CUSTOMER_ID',
	    'type' => 'varchar',
	    'module' => 'Contacts',
	    'help' => 'Stripe Customer',
	    'comment' => 'Stripe Customer ID',
	    'default_value' => '',
	    'max_size' => 255,
	    'required' => false, // true or false
	    'reportable' => true, // true or false
	    'audited' => false, // true or false
	    'importable' => 'true', // 'true', 'false', 'required'
	    'duplicate_merge' => false, // true or false
	),
	array(
	    'name' => 'stripe_customer_id',
	    'label' => 'LBL_STRIPE_CUSTOMER_ID',
	    'type' => 'varchar',
	    'module' => 'Leads',
	    'help' => 'Stripe Customer',
	    'comment' => 'Stripe Customer ID',
	    'default_value' => '',
	    'max_size' => 255,
	    'required' => false, // true or false
	    'reportable' => true, // true or false
	    'audited' => false, // true or false
	    'importable' => 'true', // 'true', 'false', 'required'
	    'duplicate_merge' => false, // true or false
	)
  ),	
  'relationships' => 
  array (
    0 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/sc_stripepayments_contactsMetaData.php',
    ),
    1 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/sc_stripepayments_accountsMetaData.php',
    ),
    2 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/sc_stripepayments_leadsMetaData.php',
    ),
  ),
  'image_dir' => '<basepath>/icons',
  'copy' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/modules/sc_StripePayments',
      'to' => 'modules/sc_StripePayments',
    ),
    1 =>
    array (
      'from' => '<basepath>/logic.php',
      'to' => 'custom/modules/Accounts/sc_accounts_logic.php',
    ),
    2 =>
    array (
      'from' => '<basepath>/logic.php',
      'to' => 'custom/modules/Leads/sc_leads_logic.php',
    ),
    3 =>
    array (
      'from' => '<basepath>/logic.php',
      'to' => 'custom/modules/Contacts/sc_contacts_logic.php',
    ),
  ),
  'language' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sc_StripePayments.php',
      'to_module' => 'sc_StripePayments',
      'language' => 'en_us',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Contacts.php',
      'to_module' => 'Contacts',
      'language' => 'en_us',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sc_StripePayments.php',
      'to_module' => 'sc_StripePayments',
      'language' => 'en_us',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'en_us',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sc_StripePayments.php',
      'to_module' => 'sc_StripePayments',
      'language' => 'en_us',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Leads.php',
      'to_module' => 'Leads',
      'language' => 'en_us',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/en_us.lang.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
  ),
  'vardefs' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/sc_stripepayments_contacts_sc_StripePayments.php',
      'to_module' => 'sc_StripePayments',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/sc_stripepayments_contacts_Contacts.php',
      'to_module' => 'Contacts',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/sc_stripepayments_accounts_sc_StripePayments.php',
      'to_module' => 'sc_StripePayments',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/sc_stripepayments_accounts_Accounts.php',
      'to_module' => 'Accounts',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/sc_stripepayments_leads_sc_StripePayments.php',
      'to_module' => 'sc_StripePayments',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/sc_stripepayments_leads_Leads.php',
      'to_module' => 'Leads',
    ),
  ),
  'layoutfields' => 
  array (
    0 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
    1 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
    2 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
  ),
  //LOGIC HOOK STUFF
  'logic_hooks' => array(
    // logic hook for Accounts module
    array( 
      'module' => 'Accounts',
      'hook' => 'after_ui_frame',
      'order' => 33,
      'description' => 'Builds Stripe Payment Button',
      'file' => 'custom/modules/Accounts/sc_accounts_logic.php',
      'class' => 'SugarLogic',
      'function' => 'add_action_button',
    ),
     array( 
      'module' => 'Leads',
      'hook' => 'after_ui_frame',
      'order' => 33,
      'description' => 'Builds Stripe Payment Button',
      'file' => 'custom/modules/Leads/sc_leads_logic.php',
      'class' => 'SugarLogic',
      'function' => 'add_action_button',
    ),
     array( 
      'module' => 'Contacts',
      'hook' => 'after_ui_frame',
      'order' => 33,
      'description' => 'Builds Stripe Payment Button',
      'file' => 'custom/modules/Contacts/sc_contacts_logic.php',
      'class' => 'SugarLogic',
      'function' => 'add_action_button',
    ),
  ),
);